_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.5
            "6": 4.45.2
            "8":
                - 2
                - 5
            "12": 0.18.5
            "13": linux-x86_64
attention_sink_size:
    value: 4
experiment:
    value: stream
window_size:
    value: 4096
